
default:
	@echo portaudio/asio
	@cd asio
	@$(MAKE) /nologo
	@echo portaudio/win
	@cd ../win
	@$(MAKE) /nologo
	@cd ..

clean:
	@echo portaudio/asio
	@cd asio
	@$(MAKE) /nologo clean
	@echo portaudio/win
	@cd ..\win
	@$(MAKE) /nologo clean
	@cd ..
